### ISSUE TITLE
The link for the jdk download no longer works and the orchestrator install fails

### ISSUE THREAD

**Issue by abarbulescu** [Morphl-AI/MorphL-Orchestrator#16]
![Screenshot from 2019-04-15 14-11-16](https://user-images.githubusercontent.com/20221509/56128493-6d923480-5f88-11e9-86dd-1b8df4aa5544.png)

**Comment by anghelalexandra** [comment]
Closed by https://github.com/Morphl-AI/MorphL-Orchestrator/pull/17
